### ISSUE TITLE
Cannot find /opsguide/tasks_rec_alloc_pcf partial

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/docs-dev-guide#147]
`using-tasks.html.md.erb` conditionally uses the partial `<%= partial '../opsguide/tasks_rec_alloc_pcf' %>`. Since our `product_name` is `APC`, the template tries to load that partial. I have no idea where the partial should come from or how I should provide it. Furthermore, I think hardcoding an if statement to check for a `product_name` of `PWS` is wrong because it refers to a specific cloud foundry provider which i think must not be hardcoded in the CF docs.

**Comment by pspinrad** [comment]
Thanks @mastertinner - we [changed](https://github.com/cloudfoundry/docs-dev-guide/commit/5f871cd53f6a67e65a346b1861f3602e2b93a3e9) the order of the logic so that books with product names besides "PCF", like the OS CF docs, will use the partial here in docs-dev-guide.  Re not referring to a product name or acronym in the CF docs, we agree that it's an issue and have tried a couple different approaches to avoid this, all of them sub-optimal given current tooling.

**Comment by mastertinner** [comment]
Thanks for the quick reply, @pspinrad!
