### ISSUE TITLE
Clarify app lifecycle signals during shutdown

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/docs-dev-guide#290]
In https://docs.cloudfoundry.org/devguide/deploy-apps/app-lifecycle.html#shutdown it says:

> When CF requests a shutdown of your app instance, either in response to the command `cf scale APPNAME -i NUMBER-OF-INSTANCES` or because of a system event, CF sends [...]

There are a couple of confusing points for users about this:

- We explicitly mention `cf scale`, but we don't say anything about `cf stop`, `cf delete` or even `cf push` (when pushing a new version of an existing app)
- What is "a system event"? (users are unlikely to be familiar with implementation details of CF, so this should be made explicit)

**Comment by ljarzynski** [comment]
@CAFxX Thanks for creating this issue! I think there may be an opportunity to add detail to the page as you have suggested. 

I'd like to bring in Diego PM @emalm to help. Eric- would you be able to speak to the points above? 

I am happy to incorporate any clarifying information into the doc.

**Comment by emalm** [comment]
Thanks, @CAFxX and @ljarzynski. Whenever CF stops an app instance intentionally, it will follow that `TERM`-wait-`KILL` pattern of process signals. Those cases include the `cf scale` case above, but also when an app is stopped because of `cf stop`, `cf push`, or `cf delete`, when an individual app instance is stopped with `cf restart-app-instance` or at the end of the replacement procedure during Diego cell evacuation, and when an app instance is stopped because it fails a health-check probe.

As an exception to these cases, I believe that if monit restarts, say, the cell rep or the Garden server processes after one of them crashes, they will stop any still-running app instances by immediately destroying their containers, which would then SIGKILL the containerized processes without the initial warning TERM signal.

@ljarzynski, I'd be happy to work with you to elaborate these cases more clearly in the CF docs.

**Comment by ljarzynski** [comment]
Thanks again both! I've pushed a commit that clarifies this section: https://github.com/cloudfoundry/docs-dev-guide/commit/e28b197bbff184b85d362fad250cabd3a5455046. It will appear on the site shortly.
