### ISSUE TITLE
Blue-Green Deployment: "cf push ... -n" not supported anymore

### ISSUE THREAD

**Issue by teentitansgo** [cloudfoundry/docs-dev-guide#475]
In [Using Blue-Green Deployment](https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html), the command `cf push Blue -n demo-time` etc is used to push the app with a different host name. This is not possible anymore in the newest version of the CF CLI.

Not sure what approach in V7 would be, specify and change a route in the manifest?

**Comment by anita-flegg** [comment]
@Gerg , any suggestions?

**Comment by Gerg** [comment]
In general, the [v7 upgrade guide](https://docs.cloudfoundry.org/cf-cli/v7.html) is a good resource. Since the v6 CLI is no longer supported, we should probably update the docs to use a more modern CLI version.

cc @cloudfoundry/wg-app-runtime-interfaces-cli-approvers @cloudfoundry/wg-app-runtime-interfaces-cli-reviewers for additional help.

**Comment by FloThinksPi** [comment]
@teentitansgo @Gerg imho that part of the docs is invalid now with V7 and V8 CLIs. They way someone would take to rebuild a true blue-green behaviour is to use the routes subcommands so e.g. `create-route`, `map-route` and `unmap-route` etc. i would assume.
So makes sense to go over that doc since it also makes sense to offer an alternative to the depricated and ancient blue-green cli plugin when it comes to convince consumers to change from the V2 to the CF V3 API. :)
